### ISSUE TITLE
Dead link in CFP page

### ISSUE THREAD

**Issue by djmitche** [outreachy/website#463] opened 2021-02-12 16:17 UTC
STR:
* visit https://www.outreachy.org/communities/cfp/mozilla/
* click "Mentor requirements"

https://www.outreachy.org/communities/cfp/mozilla/mentor/#mentor does not exist.

**Comment by sagesharp** [comment] 2021-02-15 16:37
This is a duplicate of #330. I was leaving it as newcomer friendly bug for someone to fix, but there's been enough complaints about it that I'll just fix it. Committing the fix shortly.

**Comment by djmitche** [comment] 2021-02-15 16:45
Sorry to miss the dupe!

**Closed** 2021-02-15 16:49 UTC
